server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=r34Acm
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=manager

spring.application.name=manager

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678

# spring.jpa.show-sql=true

# Gerceklesen sql durumlarının console da gosteren kod
spring.jpa.properties.hibernate.format_sql=true
# Flyway ile cakısmasın diye tavsiye:
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# 🔍 openssl rand base64 32 (terminal'de çalıştırıp çıktıyı jwt.secret'e yapıştırabilirsiniz)
app.jwt.secretKey=6sb9393iifk73HhyObqMbEHmRFcEk2AObVltA6rVIRgTXvD/OpnQrrQk6F0gQdXr6hli23zs95o/d8q6PcFHjg==
app.jwt.expirationMs=900000
app.jwt.refresh-token-days=14


admin.initial-username=admin
admin.initial-password=r34Acm.123


security.whitelisted-ips=127.0.0.1,::1